### ISSUE TITLE
KeyError: "GLEAN: 'Panini_MFR is not in the model registry'"

### ISSUE THREAD

**Issue by GeorvityLabs** [wyhuai/Panini-Net#1]
hi @wyhuai ,

great paper!

I tried making a colab notebook , link to it is this : 
https://colab.research.google.com/drive/1IJ8OOqdNmj2_qxexwDiyoEoZ-mRoA3yC?usp=sharing

But , I am getting an error when trying to run inference 

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/content/mmediting/mmedit/models/restorers/srgan.py", line 51, in __init__
    self.generator = build_backbone(generator)
  File "/content/mmediting/mmedit/models/builder.py", line 31, in build_backbone
    return build(cfg, BACKBONES)
  File "/content/mmediting/mmedit/models/builder.py", line 22, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 45, in build_from_cfg
    f'{obj_type} is not in the {registry.name} registry')
KeyError: 'Panini_MFR is not in the model registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo/restoration_single_face_demo.py", line 65, in <module>
    main()
  File "demo/restoration_single_face_demo.py", line 48, in main
    args.config, args.checkpoint, device=torch.device('cuda', args.device))
  File "/content/mmediting/mmedit/apis/matting_inference.py", line 31, in init_model
    model = build_model(config.model, test_cfg=config.test_cfg)
  File "/content/mmediting/mmedit/models/builder.py", line 60, in build_model
    return build(cfg, MODELS, dict(train_cfg=train_cfg, test_cfg=test_cfg))
  File "/content/mmediting/mmedit/models/builder.py", line 22, in build
    return build_from_cfg(cfg, registry, default_args)
  File "/usr/local/lib/python3.7/dist-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
KeyError: "GLEAN: 'Panini_MFR is not in the model registry'"
```

hope you can kindly suggest , have a look into my notebook and suggest a solution for the problem.

**Comment by wyhuai** [comment]
@GeorvityLabs  Thanks for your attention! This problem is caused by wrongly calling into the official mmediting folder "content/mmediting", which is created when you install the MMCV. Simply deleting that folder may solve your problem.

**Comment by GeorvityLabs** [comment]
@wyhuai thank you , yes that did solve the problem!
